services:
  postgres:
    image: postgres
    container_name: postgres-command
    hostname: postgres-command
    environment:
      - POSTGRES_DB=userPostgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    ports:
      - "3342:5432"
    networks:
      - users-network
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - users-network
    volumes:
      - "D:/rabbitmq/rabbitmq-data:/var/lib/rabbitmq"
      - "D:/rabbitmq/rabbitmq-log:/var/log/rabbitmq"

networks:
  users-network:
    driver: bridge
