services:
  postgres:
    image: postgres
    container_name: postgres-command
    hostname: postgres-command
    environment:
      - POSTGRES_DB=userPostgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    ports:
      - "3342:5432"
    networks:
      - users-network
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - users-network
    volumes:
      - "D:/rabbitmq/rabbitmq-data:/var/lib/rabbitmq"
      - "D:/rabbitmq/rabbitmq-log:/var/log/rabbitmq"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - users-network
    volumes:
      - "D:/db-mongodb:/data/db"
      - "./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh"

networks:
  users-network:
    driver: bridge
